# Generated by Django 5.1.5 on 2025-02-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(blank=True, max_length=50, null=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('canceled', 'Canceled')], default='scheduled', max_length=10)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('home_win_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('draw_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_win_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_bet_available', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sports.league')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time', 'status'], name='sports_matc_start_t_8373ae_idx'), models.Index(fields=['league', 'status'], name='sports_matc_league__fff5ad_idx')],
            },
        ),
    ]
