# Generated by Django 5.1.5 on 2025-02-22 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_choice', models.CharField(choices=[('home', 'Home Win'), ('draw', 'Draw'), ('away', 'Away Win')], max_length=4)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], default='pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='sports.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_odds', models.DecimalField(decimal_places=2, max_digits=7)),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matches', models.ManyToManyField(related_name='bet_slips', through='sports.Bet', to='sports.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='sports.betslip'),
        ),
        migrations.AddIndex(
            model_name='betslip',
            index=models.Index(fields=['user', 'status'], name='sports_bets_user_id_a20f38_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['bet_slip', 'status'], name='sports_bet_bet_sli_017b96_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['match', 'status'], name='sports_bet_match_i_9de3cf_idx'),
        ),
    ]
