# Generated by Django 5.1.5 on 2025-03-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_bet_betslip_bet_bet_slip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='data_source',
            field=models.CharField(choices=[('flashscore', 'Flashscore')], default='flashscore', max_length=20),
        ),
        migrations.AddField(
            model_name='league',
            name='source_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='last_odds_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='source_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('canceled', 'Canceled'), ('prepared', 'Prepared')], default='prepared', max_length=10),
        ),
    ]
