# Generated by Django 5.1.5 on 2025-06-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_league_data_source_league_source_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='bet',
            name='bet_choice',
        ),
        migrations.CreateModel(
            name='BetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_options', to='sports.match')),
                ('bet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_options', to='sports.bettype')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='sports.betoption'),
        ),
    ]
